# service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: garden-app-monitor
  namespace: monitoring-metrics
  labels:
    app: garden-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: garden-app
  namespaceSelector:
    matchNames:
      - garden-app
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
      scrapeTimeout: 10s
    - port: http
      path: /q/health/ready
      interval: 30s
      scrapeTimeout: 5s